name: build and release

on:
  push:
    branches:
      - master  # 或者你想要触发这个工作流的分支名
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write  # 根据需要设置适当的权限
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # 指定一个具体的Node.js版本

      - name: 安装依赖
        run: npm install

      - name: 构建项目
        run: npm run build

      - name: 获取当前版本号
        id: get_version
        run: |
          # 获取最新的版本号标签
          current_version=$(git tag | grep '^v[0-9]\+\.[0-9]\+$' | sort -V | tail -n 1)

          # 如果没有找到版本号，默认为 v0.1
          if [ -z "$current_version" ]; then
            current_version="v0.1"
          fi

          # 提取版本号前缀和后缀
          version_prefix=${current_version%.*}
          version_suffix=${current_version##*.}

          # 递增后缀
          new_version_suffix=$((version_suffix + 1))

          # 拼接新的版本号
          new_version="${version_prefix}.${new_version_suffix}"

          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "生成的新版本号: $new_version"  # 输出新的版本号

      - name: 创建发布
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_version }}
          release_name: Release ${{ env.new_version }}
          draft: false
          prerelease: false

      - name: 压缩dist文件夹
        run: zip -r your-build-file.zip ./dist

      - name: 上传构建文件到GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./your-build-file.zip
          asset_name: your-build-file.zip
          asset_content_type: application/zip
